apiVersion: v1
kind: Service
metadata:
  name: api-gateway-dev-service
spec:
  selector:
    app: api-gateway-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
